-- 코드를 작성해주세요
WITH FIND_IS_NULL AS (
    SELECT I1.ITEM_ID AS NULL_ID
    FROM ITEM_INFO I1 LEFT JOIN ITEM_TREE T
    ON I1.ITEM_ID = T.PARENT_ITEM_ID
    WHERE PARENT_ITEM_ID IS NULL  
)

SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM FIND_IS_NULL F JOIN ITEM_INFO I
ON F.NULL_ID = I.ITEM_ID
ORDER BY I.ITEM_ID DESC


