-- 코드를 입력하세요
WITH CAR_TYPE_FIND AS (
    SELECT CAR_ID, (DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30) AS RENTAL
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN JOIN CAR_RENTAL_COMPANY_CAR CAR
    ON PLAN.CAR_TYPE = CAR.CAR_TYPE
    WHERE DURATION_TYPE = '30일 이상' AND (DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30) >= 500000
    AND (DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30) < 2000000
    AND CAR.CAR_TYPE IN ('세단', 'SUV')
    GROUP BY CAR_ID
)


SELECT FIND.CAR_ID, CAR.CAR_TYPE, ROUND(FIND.RENTAL, 0) AS FEE
FROM CAR_TYPE_FIND FIND JOIN CAR_RENTAL_COMPANY_CAR CAR 
ON FIND.CAR_ID = CAR.CAR_ID
WHERE FIND.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, FIND.CAR_ID DESC

