-- 코드를 입력하세요
WITH FIND_BEST AS (
    SELECT REST_ID, FOOD_TYPE, RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK
    FROM REST_INFO
)

SELECT F.FOOD_TYPE, F.REST_ID, REST_NAME, FAVORITES
FROM REST_INFO I JOIN FIND_BEST F ON I.REST_ID = F.REST_ID
WHERE RNK = 1
ORDER BY F.FOOD_TYPE DESC
