-- 코드를 입력하세요
WITH FIND_MAX_REVIEW AS (
    SELECT REST_ID, FOOD_TYPE, RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK
    FROM REST_INFO
)

SELECT R.FOOD_TYPE, R.REST_ID, REST_NAME, FAVORITES
FROM FIND_MAX_REVIEW R JOIN REST_INFO I ON R.REST_ID = I.REST_ID
WHERE RNK = 1
ORDER BY R.FOOD_TYPE DESC