WITH COLONY_RANK AS (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANK_NUM
    FROM ECOLI_DATA
)

SELECT E1.ID, 
    (CASE WHEN RANK_NUM = 1 THEN 'CRITICAL'
        WHEN RANK_NUM = 2 THEN 'HIGH'
        WHEN RANK_NUM = 3 THEN 'MEDIUM'
        WHEN RANK_NUM = 4 THEN 'LOW'
    END) AS COLONY_NAME
FROM ECOLI_DATA E1 JOIN COLONY_RANK C
ON E1.ID = C.ID
ORDER BY E1.ID;

