-- 코드를 작성해주세요
WITH RANKING AS (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS NUMBER
    FROM ECOLI_DATA
)

SELECT ID,
    CASE 
        WHEN NUMBER = 1 THEN 'CRITICAL'
        WHEN NUMBER = 2 THEN 'HIGH'
        WHEN NUMBER = 3 THEN 'MEDIUM'
        WHEN NUMBER = 4 THEN 'LOW'
    END AS COLONY_NAME
FROM RANKING 
ORDER BY ID ASC
