-- 코드를 입력하세요
WITH FIND_JOIN AS (
    SELECT USER_ID, COUNT(USER_ID) AS JOIN_COUNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USER,
ROUND(COUNT(DISTINCT USER_ID) / (SELECT JOIN_COUNT FROM FIND_JOIN), 1) AS PURCHASE_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC