-- 코드를 작성해주세요
WITH RECURSIVE COUNT_ECOLI AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, C.GENERATION + 1
    FROM ECOLI_DATA E JOIN COUNT_ECOLI C
    ON E.PARENT_ID = C.ID
    
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM COUNT_ECOLI
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION 
ORDER BY GENERATION ASC