## 구 ) 자식이 없는 개체의 수와 세대

WITH RECURSIVE FIND_GENERATION AS (
    ## 앵커
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT C.ID, GENERATION + 1
    FROM ECOLI_DATA C JOIN FIND_GENERATION G
    ON G.ID = C.PARENT_ID
)

SELECT COUNT(F.ID) AS COUNT, GENERATION
FROM FIND_GENERATION F
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA E
    WHERE E.PARENT_ID = F.ID 
)
GROUP BY GENERATION
ORDER BY GENERATION ASC
