WITH FIND_JULY_MAX AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT J.FLAVOR
FROM FIND_JULY_MAX J JOIN FIRST_HALF H
ON J.FLAVOR = H.FLAVOR
GROUP BY J.FLAVOR
ORDER BY SUM(J.TOTAL_ORDER + H.TOTAL_ORDER) DESC
LIMIT 3