-- 코드를 작성해주세요
WITH FIND_FRONT_END AS (
    SELECT SUM(CODE) AS MASK
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (
    SELECT MASK
    FROM FIND_FRONT_END
) > 0
ORDER BY ID ASC


