-- 코드를 작성해주세요

WITH AVERAGE AS (
    SELECT E.EMP_NO, AVG(SCORE) AS SCORE
    FROM HR_EMPLOYEES E JOIN HR_GRADE G
    ON E.EMP_NO = G.EMP_NO
    GROUP BY EMP_NO
)

SELECT E.EMP_NO, E.EMP_NAME, (
    CASE WHEN A.SCORE >= 96 THEN 'S'
    WHEN A.SCORE >= 90 THEN 'A'
    WHEN A.SCORE >= 80 THEN 'B'
    ELSE 'C'
    END
) AS GRADE, ROUND((
        CASE WHEN A.SCORE >= 96 THEN SAL * 0.2
        WHEN A.SCORE >= 90 THEN SAL * 0.15
        WHEN A.SCORE >= 80 THEN SAL * 0.1
        ELSE 'C'
        END
), 0) AS BONUS
FROM AVERAGE A JOIN HR_EMPLOYEES E
ON A.EMP_NO = E.EMP_NO
ORDER BY E.EMP_NO ASC