WITH CHECK_GRADE AS (
    SELECT H.EMP_NO, SUM(H.SAL) AS TOTAL_SAL,
        CASE WHEN AVG(G.SCORE) >= 96 THEN 'S'
            WHEN AVG(G.SCORE)  >= 90 THEN 'A'
            WHEN AVG(G.SCORE)  >= 80 THEN 'B'
            ELSE 'C'
        END AS GRADE
    FROM HR_EMPLOYEES H JOIN HR_GRADE G
    ON H.EMP_NO = G.EMP_NO
    GROUP BY EMP_NO
)

SELECT C.EMP_NO, E.EMP_NAME, GRADE,
    CASE WHEN GRADE = 'S' THEN C.TOTAL_SAL * 0.2 / 2
        WHEN GRADE = 'A' THEN C.TOTAL_SAL * 0.15 / 2
        WHEN GRADE = 'B' THEN C.TOTAL_SAL * 0.1 / 2
        ELSE C.TOTAL_SAL * 0
        END AS BONUS
FROM CHECK_GRADE C JOIN HR_EMPLOYEES E 
ON C.EMP_NO = E.EMP_NO
ORDER BY C.EMP_NO ASC

