-- 코드를 입력하세요
WITH FIND_MAX AS (
    SELECT M.MEMBER_ID
    FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
    GROUP BY M.MEMBER_ID 
    ORDER BY COUNT(REVIEW_ID) DESC
    LIMIT 1
)

SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM FIND_MAX M JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
JOIN MEMBER_PROFILE P ON P.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
