-- 코드를 작성해주세요
WITH RARITY AS (
    SELECT T.ITEM_ID
    FROM ITEM_INFO I JOIN ITEM_TREE T
    ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE RARITY = 'RARE'
)


SELECT R.ITEM_ID, ITEM_NAME, RARITY
FROM RARITY R JOIN ITEM_INFO I ON R.ITEM_ID = I.ITEM_ID
ORDER BY R.ITEM_ID DESC


