-- 코드를 작성해주세요
SELECT I1.ITEM_ID, I1.ITEM_NAME, I1.RARITY
FROM 
    ITEM_INFO I 
JOIN 
    ITEM_TREE T
ON 
    I.ITEM_ID = T.PARENT_ITEM_ID
JOIN
    ITEM_INFO I1
ON 
    I1.ITEM_ID = T.ITEM_ID
WHERE I.RARITY = 'RARE'
ORDER BY I1.ITEM_ID DESC