-- 코드를 작성해주세요
# 부모의 형질과 &
# 부모의 아이디의 형질과 자식의 GENOTYPE 비교


SELECT E1.ID, E1.GENOTYPE, E2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA E1 JOIN ECOLI_DATA E2
ON E1.PARENT_ID = E2.ID
WHERE (E2.GENOTYPE & E1.GENOTYPE) = E2.GENOTYPE
ORDER BY E1.ID ASC