-- 코드를 입력하세요
WITH COUNT_CAR_RENTAL AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

SELECT MONTH(H.START_DATE) AS MONTH, H.CAR_ID, COUNT(*) AS RECORDS
FROM COUNT_CAR_RENTAL C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
ON C.CAR_ID = H.CAR_ID
WHERE H.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY H.CAR_ID, MONTH(H.START_DATE)
ORDER BY MONTH ASC, H.CAR_ID DESC