-- 코드를 작성해주세요
WITH FIND_MAX_ECOLI AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR , MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR, ABS(E.SIZE_OF_COLONY - MAX_SIZE) AS YEAR_DEV, E.ID
FROM FIND_MAX_ECOLI M JOIN ECOLI_DATA E
ON M.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC

