WITH FISH_TYPE_CHECK AS (
    SELECT FISH_TYPE
    FROM FISH_NAME_INFO
    WHERE FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER'
)

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_TYPE_CHECK C JOIN FISH_INFO I ON C.FISH_TYPE = I.FISH_TYPE