-- 코드를 작성해주세요
WITH RANKED AS (
    SELECT I.ID, N.FISH_NAME, I.LENGTH,
    RANK() OVER(PARTITION BY N.FISH_TYPE ORDER BY LENGTH DESC) AS RNK
    FROM FISH_INFO I JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
)

SELECT ID, FISH_NAME, LENGTH
FROM RANKED
WHERE RNK = 1
ORDER BY ID