-- 코드를 작성해주세요

WITH FIND_MAX_LENGTH AS (
    SELECT I.FISH_TYPE, MAX(LENGTH) AS FISH_LENGTH
    FROM FISH_INFO I JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY FISH_TYPE
)

SELECT I.ID, FISH_NAME, FISH_LENGTH AS LENGTH
FROM FISH_INFO I JOIN FIND_MAX_LENGTH L
ON I.FISH_TYPE = L.FISH_TYPE
JOIN FISH_NAME_INFO N
ON L.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH = FISH_LENGTH
ORDER BY I.ID ASC