-- 물고기 종류 별로 가장 큰 물고기 
WITH BIG_FISH AS (
    SELECT N.FISH_TYPE, MAX(LENGTH) OVER (PARTITION BY N.FISH_TYPE) AS LENGTH, FISH_NAME
    FROM FISH_INFO I1 JOIN FISH_NAME_INFO N
    ON I1.FISH_TYPE = N.FISH_TYPE
)

SELECT DISTINCT(ID), B.FISH_NAME, B.LENGTH
FROM BIG_FISH B JOIN FISH_INFO I
ON B.LENGTH = I.LENGTH AND B.FISH_TYPE = I.FISH_TYPE