-- 코드를 입력하세요
WITH FIND_SALES AS (
    SELECT S.BOOK_ID, SUM(SALES) AS NUM
    FROM BOOK_SALES S JOIN BOOK B
    ON S.BOOK_ID = B.BOOK_ID
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY S.BOOK_ID
)

SELECT CATEGORY, SUM(NUM) AS TOTAL_SALES
FROM FIND_SALES F JOIN BOOK B
ON F.BOOK_ID = B.BOOK_ID
GROUP BY CATEGORY 
ORDER BY CATEGORY ASC

    