-- 코드를 작성해주세요
WITH FIND_AVERAGE AS (
    SELECT FISH_TYPE, AVG(CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END) AS AVGFISH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVGFISH >= 33
)

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, I.FISH_TYPE
FROM FIND_AVERAGE A JOIN FISH_INFO I ON A.FISH_TYPE = I.FISH_TYPE
GROUP BY I.FISH_TYPE
ORDER BY I.FISH_TYPE ASC
