WITH FRONT_END_MASKS AS (
    SELECT SUM(CODE) AS FE_CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
), C_SHARP AS (
    SELECT CODE 
    FROM SKILLCODES
    WHERE NAME = 'C#'
), PYTHON AS (
    SELECT CODE 
    FROM SKILLCODES
    WHERE NAME = 'Python'
)

SELECT 
    CASE WHEN SKILL_CODE & (SELECT FE_CODE FROM FRONT_END_MASKS) > 0 AND 
                SKILL_CODE & (SELECT CODE FROM PYTHON) = (SELECT CODE FROM PYTHON) THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM C_SHARP) = (SELECT CODE FROM C_SHARP) THEN 'B'
        WHEN SKILL_CODE & (SELECT FE_CODE FROM FRONT_END_MASKS) > 0 THEN 'C'
        END AS GRADE,
        ID, EMAIL
FROM DEVELOPERS
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID ASC